services:
    devcontainer:
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - path: ./.env
              required: true
        volumes:
            # Mount the project directory to the container
            - ../:/workspace
        networks:
            - default
        command: ['sleep', 'infinity']

networks:
    default:
        name: devcontainer
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: devcontainer
