name: build-binaries

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install project (no deps) and PyInstaller
          python -m pip install .
          python -m pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --name plex-leon src/plex_leon/cli.py

      - name: Prepare artifact
        shell: bash
        run: |
          mkdir -p artifacts
          if [ "${{ runner.os }}" = "Windows" ]; then
            cp dist/plex-leon.exe "artifacts/plex-leon-${{ runner.os }}.exe"
          else
            cp dist/plex-leon "artifacts/plex-leon-${{ runner.os }}"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plex-leon-${{ runner.os }}
          path: artifacts/*
